# @package _global_
defaults:
  - _self_
  - model: siren
  - logging: wandb
  - optimizer: adamw

image: tokyo512.png
image_dir: ../../data
image_W: 512

use_wandb: true
is_debug: false
total_steps: 3000

random_seed: [0, 1, 2]